<template>
  <footer class="footer">
    <small>
      Generated by <a href="https://fuya.info">Fuya</a>.
    </small>
  </footer>
</template>

<script lang="ts">
export default {};
</script>

<style scoped>
</style>
